includes: ["GitHub", "GitHubCommunityStandards", "GitHubRulesets"]
GitHub-url: "https://github.com/gt-sse-center/RepoAuditor"
GitHubCommunityStandards-url: "https://github.com/gt-sse-center/RepoAuditor"
GitHubRulesets-url: "https://github.com/gt-sse-center/RepoAuditor"
# GitHub-pat: "PAT"
