includes: ["GitHub", "GitHubCommunityStandards"]
GitHub-url: "https://github.com/gt-sse-center/RepoAuditor"
GitHubCommunityStandards-url: "https://github.com/gt-sse-center/RepoAuditor"
# GitHub-pat: "PAT"
