site_name: RepoAuditor
site_description: Audits repositories for best practices.
nav:
  - Home: index.md
  - Personal Access Token: PAT.md
  - Usage: usage.md
  - Config File: config_file.md
  - Writing a Custom Plugin: custom_plugin.md
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
  - Troubleshooting: troubleshooting.md
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime

plugins:
  - termynal

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      # auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:  # render emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
