site_name: RepoAuditor
site_description: Audits repositories for best practices.
nav:
  - Home: index.md
  - PAT: PAT.md
  - Usage: usage.md
  - Config File: config_file.md
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
  - Troubleshooting: troubleshooting.md
theme:
  name: material

# Extensions to render emojis
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
