name: "End To End Tests"
run-name: EndToEnd ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 * * * *' # Once every hour
  workflow_dispatch:

permissions: {}

jobs:
  EndToEnd_Workflow:
    strategy:
      fail-fast: false

      matrix:
        # Since the system under test here is the GitHub API, it is sufficient to test using only a single OS.
        os: ["ubuntu-latest"]
        # Similar to OS, we only test the lowest and highest supported versions.
        python_version: ["3.10", "3.13"]

    name: "End To End Workflow"
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python_version }}
          enable-cache: true

      - name: Dump 'github' Context
        shell: bash
        run: |
          set +e

          echo "--------------------------------------------------------------------------------"
          echo "github"
          echo "--------------------------------------------------------------------------------"
          echo ""

          cat > _github_context <<END_OF_CONTENT
          ${{ toJSON(github) }}
          END_OF_CONTENT

          cat _github_context

          exit 0

      # BugBug - name: Should Periodic Workflow Run?
      # BugBug   run: uv run python .github/tools/ShouldPeriodicWorkflowRun ${{ github.
