name: RepoAuditor

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  audit-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: mtanneau/RepoAuditor@action-v0.2.1
        with:
          github_pat: ${{ secrets.REPO_AUDITOR_PAT }}
